apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditlogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditlogservice
  template:
    metadata:
      labels:
        app: auditlogservice
    spec:
      containers:
      - name: auditlogservice
        image: pitstop/auditlogservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
