apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagementapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagementapi
  template:
    metadata:
      labels:
        app: customermanagementapi
    spec:
      containers:
      - name: customermanagementapi
        image: pitstop/customermanagementapi:1.0
        ports:
        - containerPort: 5100
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production

---
apiVersion: v1
kind: Service
metadata:
  name: customermanagementapi
spec:
  ports:
  - port: 5100
    targetPort: 5100
  selector:
    app: customermanagementapi
