apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoiceservice
  template:
    metadata:
      labels:
        app: invoiceservice
    spec:
      containers:
      - name: invoiceservice
        image: pitstop/invoiceservice:1.0
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
