apiVersion: apps/v1
kind: Deployment
metadata:
  name: logserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logserver
  template:
    metadata:
      labels:
        app: logserver
    spec:
      containers:
      - name: logserver
        image: datalust/seq:latest
        ports:
        - containerPort: 80
        env:
        - name: ACCEPT_EULA
          value: "Y"

---
apiVersion: v1
kind: Service
metadata:
  name: logserver
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: logserver
