apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - name: mailserver
        image: maildev/maildev:1.1.0
        ports:
        - containerPort: 25
        - containerPort: 80
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: mailserver
spec:
  ports:
  - name: smtp
    port: 25
    targetPort: 25
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: mailserver
