apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: sqlserverdata
          mountPath: /var/opt/mssql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Developer
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: sa-password
      volumes:
      - name: sqlserverdata
        persistentVolumeClaim:
          claimName: sqlserverdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlserver

--- 
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
data:
  SA_PASSWORD: Ojh0a0doNDdoTmQ4OUhhcThMTjI=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserverdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
