apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclemanagementapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehiclemanagementapi
  template:
    metadata:
      labels:
        app: vehiclemanagementapi
    spec:
      containers:
      - name: vehiclemanagementapi
        image: pitstop/vehiclemanagementapi:1.0
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: vehiclemanagementapi
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: vehiclemanagementapi
