apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagementapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshopmanagementapi
  template:
    metadata:
      labels:
        app: workshopmanagementapi
    spec:
      containers:
      - name: workshopmanagementapi
        image: pitstop/workshopmanagementapi:1.0
        ports:
        - containerPort: 5200
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production

---
apiVersion: v1
kind: Service
metadata:
  name: workshopmanagementapi
spec:
  ports:
  - port: 5200
    targetPort: 5200
  selector:
    app: workshopmanagementapi
